export const concertRankSlides = [
  {
    id: 1,
    title: '뮤지컬 데스노트(The Musical Death Note)',
    location: '디큐브 링크아트센터',
    date: ['2025.10.14', '20226.5.10'],
    imgUrl: '/concert-rank-banner/concert_rank_banner_1.gif',
  },
  {
    id: 2,
    title: '뮤지컬 <한복 입은 남자>',
    location: '충무아트센터 대극장',
    date: ['2025.12.2', '2026.3.8'],
    imgUrl: '/concert-rank-banner/concert_rank_banner_2.gif',
  },
  {
    id: 3,
    title: '<센과 치히로의 행방불명> 오리지널 투어 (SPRITED AWAY)',
    location: '예술의 전당 오페라 극장',
    date: ['2026.1.7', '2026.3.22'],
    imgUrl: '/concert-rank-banner/concert_rank_banner_3.gif',
  },
  {
    id: 4,
    title: '뮤지컬 <물랑루즈!> (Moulin Rouge! The Musical)',
    location: '블루스퀘어 신한카드홀',
    date: ['2025.11.7', '2026.3.22'],
    imgUrl: '/concert-rank-banner/concert_rank_banner_4.gif',
    privateSale: true,
  },
  {
    id: 5,
    title: '뮤지컬 <이터니티>',
    location: 'NOL 유니플렉스 1관',
    date: ['2025.12.27', '2026.3.15'],
    imgUrl: '/concert-rank-banner/concert_rank_banner_5.gif',
    seatOver: true,
  },
  {
    id: 6,
    title: '뮤지컬 <킹키부츠>',
    location: '샤롯데시어터',
    date: ['2025.12.7', '2026.3.29'],
    imgUrl: '/concert-rank-banner/concert_rank_banner_6.gif',
  },
];
